# Generated by Django 2.2 on 2021-04-19 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_pics', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='git',
            field=models.URLField(max_length=100, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='self',
            field=models.TextField(default='None', max_length=300, verbose_name='О себе'),
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, verbose_name='Токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('life_days', models.IntegerField(default=7, verbose_name='Срок действия (в днях)')),
                ('type', models.CharField(choices=[('register', 'Регистрация'), ('password_reset', 'Восстановление пароля')], default='register', max_length=20, verbose_name='Тип токена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аутентификационный токен',
                'verbose_name_plural': 'Аутентификационные токены',
            },
        ),
    ]
