# Generated by Django 2.2 on 2021-04-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210419_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': {('can_watch_users', 'может видеть список пользователей')}, 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
