# Generated by Django 2.2 on 2021-03-25 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20210324_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipe',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Заголовок'),
        ),
    ]
