# Generated by Django 2.2 on 2021-03-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_tipe_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipe',
            name='project_id',
        ),
    ]
