# Generated by Django 2.2 on 2021-03-27 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_auto_20210327_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipe',
            name='project_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='webapp.Project', verbose_name='Проект'),
        ),
    ]
