# Generated by Django 2.2 on 2021-04-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_project_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(related_name='projects', to='auth.Group', verbose_name='Команда'),
        ),
    ]
