# Generated by Django 2.2 on 2021-04-15 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_auto_20210415_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipe',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='project', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
