# Generated by Django 2.2 on 2021-04-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_auto_20210415_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('add_user_in_project', 'Добавить пользователя в проект')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
