# Generated by Django 2.2 on 2021-04-18 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_auto_20210418_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipe',
            name='tipe_team',
        ),
    ]
